import { createFileRoute, Link, notFound } from "@tanstack/react-router";
import { useState } from "react";
import { ArrowUpDown, SlidersHorizontal } from "lucide-react";
import { Button } from "../components/ui/button";
import { ProductImage } from "../components/product-image";
import { StoreFooter, StoreHeader } from "../components/store-shell";
import { catalogAssets, getCollection, products } from "../lib/catalog";

export const Route = createFileRoute("/collections/$collectionSlug")({
  loader: ({ params }) => { const collection = getCollection(params.collectionSlug); if (!collection) throw notFound(); return collection; },
  head: ({ loaderData }) => ({ meta: [{ title: `${loaderData?.name ?? "Collection"} — VYROX` }, { name: "description", content: loaderData?.copy ?? "Explore the VYROX collection." }, { property: "og:title", content: `${loaderData?.name ?? "Collection"} — VYROX` }, { property: "og:description", content: loaderData?.copy ?? "Explore the VYROX collection." }] }),
  component: CollectionPage,
});

function CollectionPage() {
  const collection = Route.useLoaderData();
  const [sort, setSort] = useState<"featured" | "low" | "high">("featured");
  const matched = products.filter((product) => product.collection === collection.slug);
  const collectionProducts = matched.length > 0 ? matched : products;
  const sorted = [...collectionProducts].sort((a, b) => sort === "low" ? a.price - b.price : sort === "high" ? b.price - a.price : 0);
  return <main className="min-h-screen bg-background text-foreground"><StoreHeader/><section className="relative min-h-[460px] overflow-hidden border-b border-border"><img src={catalogAssets.collectionsImage} alt={`${collection.name} collection`} width={1920} height={1080} className="absolute inset-0 h-full w-[400%] max-w-none object-cover" style={{ transform: `translateX(-${collection.imageIndex * 25}%)` }}/><div className="absolute inset-0 bg-gradient-to-r from-background via-background/70 to-transparent"/><div className="section-shell relative z-10 flex min-h-[460px] items-end py-12"><div className="max-w-xl"><p className="section-kicker">VYROX / Collection 0{collection.imageIndex + 1}</p><h1 className="mt-3 font-display text-6xl font-black uppercase leading-[.85] sm:text-8xl">{collection.name}</h1><p className="mt-5 text-sm text-muted-foreground">{collection.copy}</p></div></div></section><section className="section-shell py-12"><div className="flex flex-col justify-between gap-4 border-b border-border pb-5 sm:flex-row sm:items-center"><div><p className="text-xs font-bold uppercase tracking-widest">{sorted.length} pieces</p><p className="mt-1 text-[10px] text-muted-foreground">Designed in India · Made to make a statement</p></div><div className="flex items-center gap-2"><Button variant="outline" className="sm:hidden"><SlidersHorizontal className="mr-2 size-4"/>Filter</Button><label className="sr-only" htmlFor="sort">Sort products</label><div className="flex h-10 items-center border border-border px-3"><ArrowUpDown className="mr-2 size-4 text-primary"/><select id="sort" value={sort} onChange={(event) => setSort(event.target.value as typeof sort)} className="bg-background text-[10px] font-bold uppercase tracking-wider outline-none"><option value="featured">Featured</option><option value="low">Price: Low to high</option><option value="high">Price: High to low</option></select></div></div></div><div className="grid gap-3 pt-7 sm:grid-cols-2 lg:grid-cols-4">{sorted.map((product) => <Link key={product.slug} to="/product/$productSlug" params={{ productSlug: product.slug }} className="group border border-border bg-card"><ProductImage product={product} className="aspect-[4/5] transition-opacity group-hover:opacity-80"/><div className="border-t border-border p-4"><p className="mb-2 text-[9px] uppercase tracking-widest text-primary">{collection.name}</p><h2 className="text-xs font-semibold">{product.name}</h2><p className="mt-2 text-xs">₹{product.price}</p></div></Link>)}</div>{matched.length === 0 && <div className="mt-10 border border-primary/40 bg-primary/5 p-5 text-xs text-muted-foreground"><b className="text-foreground">Preview collection:</b> This edit is launching soon. Explore the current VYROX pieces while you wait.</div>}</section><StoreFooter/></main>;
}