import { createFileRoute, Link, notFound } from "@tanstack/react-router";
import { useRef, useState } from "react";
import { Check, ChevronLeft, ChevronRight, Minus, Plus, Ruler, Rotate3D, ShieldCheck, Truck, X } from "lucide-react";
import { Button } from "../components/ui/button";
import { StoreFooter, StoreHeader } from "../components/store-shell";
import { useCart } from "../components/store-state";
import { ProductImage } from "../components/product-image";
import { getProduct, products, sizes } from "../lib/catalog";

export const Route = createFileRoute("/product/$productSlug")({
  loader: ({ params }) => { const product = getProduct(params.productSlug); if (!product) throw notFound(); return product; },
  head: ({ loaderData }) => ({ meta: [{ title: `${loaderData?.name ?? "Product"} — VYROX` }, { name: "description", content: loaderData?.description ?? "Premium VYROX streetwear." }, { property: "og:title", content: `${loaderData?.name ?? "Product"} — VYROX` }, { property: "og:description", content: loaderData?.description ?? "Premium VYROX streetwear." }] }),
  component: ProductPage,
});

const angleNames = ["Front", "Quarter", "Side", "Reverse", "Back"];
const chart = [["S", "40", "27", "19"], ["M", "42", "28", "20"], ["L", "44", "29", "21"], ["XL", "46", "30", "22"], ["XXL", "48", "31", "23"]];

function ProductPage() {
  const product = Route.useLoaderData();
  const { add } = useCart();
  const [frame, setFrame] = useState(0);
  const [size, setSize] = useState<string>();
  const [quantity, setQuantity] = useState(1);
  const [showChart, setShowChart] = useState(false);
  const [error, setError] = useState(false);
  const dragStart = useRef<number>();
  const move = (direction: number) => setFrame((current) => (current + direction + 5) % 5);
  const addSelected = () => { if (!size) { setError(true); return false; } add({ slug: product.slug, size, quantity }); setError(false); return true; };

  return <main className="min-h-screen bg-background text-foreground"><StoreHeader/><div className="section-shell py-7"><div className="mb-7 flex gap-2 text-[10px] uppercase tracking-widest text-muted-foreground"><Link to="/">Home</Link><span>/</span><Link to="/collections/$collectionSlug" params={{ collectionSlug: product.collection }}>Collection</Link><span>/</span><span className="text-foreground">{product.name}</span></div><div className="grid gap-10 lg:grid-cols-[minmax(0,1.2fr)_minmax(360px,.8fr)]">
    <section><div className="relative aspect-[4/3] cursor-ew-resize touch-pan-y overflow-hidden border border-border bg-card select-none" onPointerDown={(event) => { dragStart.current = event.clientX; event.currentTarget.setPointerCapture(event.pointerId); }} onPointerUp={(event) => { if (dragStart.current !== undefined) { const delta = event.clientX - dragStart.current; if (Math.abs(delta) > 20) move(delta < 0 ? 1 : -1); dragStart.current = undefined; } }} aria-label={`360 degree view, ${angleNames[frame]} angle`}><img src={product.spinImage} alt={`${product.name}, ${angleNames[frame]} angle`} width={1920} height={512} draggable={false} className="h-full w-[500%] max-w-none object-cover transition-transform duration-300" style={{ transform: `translateX(-${frame * 20}%)` }}/><div className="absolute inset-x-0 bottom-0 flex items-center justify-between bg-gradient-to-t from-background via-background/70 to-transparent p-5 pt-14"><Button variant="outline" size="icon" onClick={() => move(-1)} aria-label="Previous angle"><ChevronLeft className="size-4"/></Button><div className="text-center"><div className="flex items-center justify-center gap-2 text-xs font-bold uppercase tracking-widest"><Rotate3D className="size-4 text-primary"/> Drag to rotate</div><p className="mt-1 text-[9px] uppercase tracking-widest text-muted-foreground">{angleNames[frame]} · {frame + 1}/5</p></div><Button variant="outline" size="icon" onClick={() => move(1)} aria-label="Next angle"><ChevronRight className="size-4"/></Button></div></div><div className="mt-3 grid grid-cols-5 gap-2">{angleNames.map((name, index) => <button key={name} type="button" onClick={() => setFrame(index)} className={`border p-2 text-[9px] font-bold uppercase tracking-wider transition-colors ${frame === index ? "border-primary text-primary" : "border-border text-muted-foreground hover:border-primary"}`}>{name}</button>)}</div></section>
    <section className="lg:sticky lg:top-24 lg:self-start"><p className="section-kicker">Limited drop · In stock</p><h1 className="mt-3 font-display text-5xl font-black uppercase leading-[.9] sm:text-6xl">{product.name}</h1><div className="mt-5 flex items-center gap-4"><span className="font-display text-3xl font-bold">₹{product.price}</span><span className="text-xs tracking-widest text-primary">★★★★★ <span className="text-muted-foreground">(48)</span></span></div><p className="mt-6 max-w-xl text-sm leading-7 text-muted-foreground">{product.description}</p><div className="mt-8 flex items-center justify-between"><p className="text-xs font-bold uppercase tracking-widest">Select size</p><Button variant="link" className="px-0" onClick={() => setShowChart(true)}><Ruler className="mr-2 size-4"/>Size chart</Button></div><div className="mt-3 grid grid-cols-5 gap-2">{sizes.map((item) => <Button key={item} variant={size === item ? "primary" : "outline"} className="px-0" onClick={() => { setSize(item); setError(false); }}>{item}</Button>)}</div>{error && <p className="mt-3 text-xs text-primary">Please select your size before continuing.</p>}<div className="mt-7"><p className="mb-3 text-xs font-bold uppercase tracking-widest">Quantity</p><div className="flex w-fit items-center border border-border"><Button variant="ghost" size="icon" onClick={() => setQuantity((value) => Math.max(1, value - 1))}><Minus className="size-4"/></Button><span className="w-12 text-center text-sm">{quantity}</span><Button variant="ghost" size="icon" onClick={() => setQuantity((value) => Math.min(10, value + 1))}><Plus className="size-4"/></Button></div></div><div className="mt-8 grid gap-3 sm:grid-cols-2"><Button className="h-13" onClick={addSelected}>Add to cart</Button><Button variant="outline" className="h-13" onClick={addSelected}>Buy now</Button></div><div className="mt-8 grid gap-4 border-y border-border py-5 text-xs sm:grid-cols-2"><span className="flex items-center gap-3"><Truck className="size-5 text-primary"/>Free shipping above ₹999</span><span className="flex items-center gap-3"><ShieldCheck className="size-5 text-primary"/>7-day easy returns</span></div><div className="mt-6 space-y-3 text-xs text-muted-foreground"><p className="flex gap-3"><Check className="size-4 shrink-0 text-primary"/>240 GSM premium combed cotton</p><p className="flex gap-3"><Check className="size-4 shrink-0 text-primary"/>Oversized unisex fit with drop shoulders</p><p className="flex gap-3"><Check className="size-4 shrink-0 text-primary"/>High-density, fade-resistant print</p></div></section>
  </div></div><section className="section-shell border-t border-border py-16"><p className="section-kicker">Complete the rotation</p><h2 className="section-title mt-2">You may also like</h2><div className="mt-8 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{products.filter((item) => item.slug !== product.slug).slice(0, 4).map((item) => <Link key={item.slug} to="/product/$productSlug" params={{ productSlug: item.slug }} className="group border border-border"><ProductImage product={item} className="aspect-[4/5]"/><div className="p-4"><h3 className="text-xs font-semibold">{item.name}</h3><p className="mt-1 text-xs">₹{item.price}</p></div></Link>)}</div></section><StoreFooter/>
  {showChart && <><div className="fixed inset-0 z-50 bg-background/80 backdrop-blur-sm" onClick={() => setShowChart(false)}/><div className="fixed left-1/2 top-1/2 z-50 w-[calc(100%-2rem)] max-w-xl -translate-x-1/2 -translate-y-1/2 border border-border bg-panel p-6" role="dialog" aria-modal="true" aria-labelledby="size-title"><div className="flex items-start justify-between"><div><p className="section-kicker">Find your fit</p><h2 id="size-title" className="font-display text-3xl font-black uppercase">Size chart</h2></div><Button variant="ghost" size="icon" onClick={() => setShowChart(false)}><X className="size-5"/></Button></div><p className="mt-3 text-xs text-muted-foreground">Garment measurements in inches. For a relaxed fit, choose your usual size.</p><div className="mt-6 overflow-x-auto"><table className="w-full text-left text-xs"><thead className="border-b border-border text-muted-foreground"><tr><th className="py-3">Size</th><th>Chest</th><th>Length</th><th>Shoulder</th></tr></thead><tbody>{chart.map((row) => <tr key={row[0]} className="border-b border-border"><td className="py-3 font-bold text-primary">{row[0]}</td><td>{row[1]}</td><td>{row[2]}</td><td>{row[3]}</td></tr>)}</tbody></table></div></div></>}
  </main>;
}